default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", nil) %>
  password: <%= ENV.fetch("DB_PASSWORD", nil) %>

development:
  <<: *default
  host: <%= ENV.fetch("DB_HOST", nil) %>
  database: arkheion_backend_development

test:
  <<: *default
  host: <%= ENV.fetch("DB_HOST", nil) %>
  database: arkheion_backend_test

production:
  <<: *default
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  database: <%= ENV["DB_NAME"] %>
